baseURL = "https://dsacleveland.firebaseapp.com/"
languageCode = "en-us"
title = "DSA Cleveland"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "DSA Cleveland"
    description = "**[DSA Cleveland](/about/)** is the local chapter of the [Democratic Socialists of America](http://www.dsausa.org), organizing throughout the Cleveland, OH metropolitan area. Welcome aboard."
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Lato" # should match the name on Google Fonts!
    profilepic = "img/dsa.jpg"

[[menu.main]]
    url = "/"
    name = "DSA Cleveland"
    weight = 1

[[menu.main]]
    url = "/event/"
    name = "Events"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 8

[[menu.main]]
    url = "/bylaws/"
    name = "Structure & Bylaws"
    weight = 9
  

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 10


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:info@dsacleveland.com"
    name = "envelope"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/DSA_Cleveland/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/dsacle/"
    name = "facebook"
    weight = 3
